SUBROUTINE FIT(X,Y,NDATA,A,B,SIGA,SIGB,CHI2)
IMPLICIT REAL*8(A-H,O-Z)
! PURPOSE: COMPUTE THE LINEAR FITTING COEFFICIENTS 
! CODE FROM THE COMMON NUMERICAL ALGORITHM SET OF VISUAL FORTRAN 2002 
! MODIFIED  2020
INTEGER MWT,NDATA
REAL*8 A,B,CHI2,Q,SIGA,SIGB,SIG(NDATA),X(NDATA),Y(NDATA)
INTEGER I
REAL*8 SIGDAT,SS,ST2,SX,SXOSS,SY,T,WT
MWT = 0
SX=0.
SY=0.
ST2=0.
B=0.
IF(MWT/=0) THEN
  SS=0.
  DO I=1,NDATA
    WT=1./(SIG(I)**2)
    SS=SS+WT
    SX=SX+X(I)*WT
    SY=SY+Y(I)*WT
  END DO
ELSE
  DO I=1,NDATA
    SX=SX+X(I)
    SY=SY+Y(I)
  END DO
  SS=FLOAT(NDATA)
ENDIF
SXOSS=SX/SS
IF(MWT/=0) THEN
  DO I=1,NDATA
    T=(X(I)-SXOSS)/SIG(I)
    ST2=ST2+T*T
    B=B+T*Y(I)/SIG(I)
  END DO
ELSE
  DO I=1,NDATA
    T=X(I)-SXOSS
    ST2=ST2+T*T
    B=B+T*Y(I)
  END DO
ENDIF
B=B/ST2
A=(SY-SX*B)/SS
SIGA=SQRT((1.+SX*SX/(SS*ST2))/SS)
SIGB=SQRT(1./ST2)
CHI2=0.
IF(MWT==0) THEN
  DO I=1,NDATA
    CHI2=CHI2+(Y(I)-A-B*X(I))**2
  END DO
  Q=1.
  SIGDAT=SQRT(CHI2/(NDATA-2))
  SIGA=SIGA*SIGDAT
  SIGB=SIGB*SIGDAT
ELSE
  DO I=1,NDATA
    CHI2=CHI2+((Y(I)-A-B*X(I))/SIG(I))**2
  END DO
!  Q=GAMMQ(0.5*(NDATA-2),0.5*CHI2)
ENDIF
END SUBROUTINE FIT
